-include $(PWD)/rules_base

DEFINES := \
	-DPLATFORM_$(PLATFORM) \
	-DBUFFERED \
	-DCPP_MEMORY \
	-DHAVE_STDINT_H \
	-D_NDEBUG \
	-DFFMPEG_ENABLED \
 	-DFFMPEG_LEGACY_API \
	-D_NO_JACK_ 

DEVKIT = /opt/miyoomini-toolchain/
CROSS_COMPILE=$(DEVKIT)bin/arm-linux-gnueabihf-

CC = $(CROSS_COMPILE)gcc
CXX = $(CROSS_COMPILE)g++
STRIP = $(CROSS_COMPILE)strip
SYSROOT     := $(shell $(CROSS_COMPILE)gcc --print-sysroot)
SDL_CFLAGS  := $(shell $(SYSROOT)/usr/bin/sdl-config --cflags)
SDL_LIBS    := $(shell $(SYSROOT)/usr/bin/sdl-config --libs)

LIBAV_PATH := arm-linux-gnueabihf/libc/usr/include
FFMPEG_CFLAGS :=  -I$(DEVKIT)/$(LIBAV_PATH)/libavformat \
				  -I$(DEVKIT)/$(LIBAV_PATH)/libavfilter \
				  -I$(DEVKIT)/$(LIBAV_PATH)/libavcodec \
				  -I$(DEVKIT)/$(LIBAV_PATH)/libavutil \

FFMPEG_LIBS := -lavformat -lavfilter -lavcodec -lavutil

$(info FFMPEG_CFLAGS: $(FFMPEG_CFLAGS))
$(info FFMPEG_LIBS: $(FFMPEG_LIBS))

INCLUDES = -Iinclude $(SDL_CFLAGS) $(FFMPEG_CFLAGS) -I$(PWD)/../sources
OPT_FLAGS  = -O3 -Ofast -fdata-sections -fdata-sections -fno-common -fno-PIC -flto -marm -mtune=cortex-a7 -mfpu=neon-vfpv4 -mfloat-abi=hard -march=armv7ve+simd

TOOLPATH=$(DEVKIT)/usr/bin
PREFIX		:=	arm-linux-gnueabihf-

CFLAGS	:=	$(DEFINES) $(INCLUDES) $(SDL_CFLAGS) $(OPT_FLAGS) -Wall  
CXXFLAGS:=	$(CFLAGS) -std=gnu++03 
LIBS	:=  -lSDL -lSDL_mixer -lpthread $(SDL_LIBS) $(FFMPEG_LIBS)
LIBDIRS	:=	$(DEVKIT)/usr/lib
LIBDIRS	+=	$(DEVKIT)/usr/include
OUTPUT = ../lgpt-miyoo
EXTENSION:= elf

%.elf: $(OFILES)
	$(CXX) $(LDFLAGS) -o $@ $(OFILES) $(LIBS)
	@$(STRIP) $@
