-include $(PWD)/rules_base

DEFINES := \
	-DPLATFORM_$(PLATFORM) \
	-DBUFFERED \
	-DCPP_MEMORY \
	-D_NDEBUG \
	-DHAVE_STDINT_H \
	-DFFMPEG_ENABLED \
	-DFFMPEG_LEGACY_API \
	-D_NO_JACK_  

DEVKIT = /opt/miyoo/
CROSS_COMPILE=$(DEVKIT)bin/arm-miyoo-linux-uclibcgnueabi-
STRIP = $(CROSS_COMPILE)strip
CC = $(CROSS_COMPILE)gcc
CXX = $(CROSS_COMPILE)g++
TOOLPATH=$(DEVKIT)/usr/bin
SYSROOT     := $(shell $(CROSS_COMPILE)gcc --print-sysroot)

SDL_CFLAGS  := $(shell $(SYSROOT)/usr/bin/sdl-config --cflags)
SDL_LIBS    := $(shell $(SYSROOT)/usr/bin/sdl-config --libs)

-include $(PWD)/rules_libav

# optimization
OPT_FLAGS  = -O3 -Ofast -fdata-sections -fdata-sections -fno-common -fno-PIC -flto -marm -mtune=cortex-a53 -mfpu=neon-vfpv4 -mfloat-abi=hard
PREFIX	:=	arm-linux-gnueabihf-
INCLUDES:=	-Iinclude $(SDL_CFLAGS) $(FFMPEG_CFLAGS) -I$(PWD)/../sources 
CFLAGS	:=	$(DEFINES) $(INCLUDES) $(OPT_FLAGS) -Wall  
CXXFLAGS:=	$(CFLAGS) -std=gnu++03 
LIBS	:=	$(SDL_LIBS) $(FFMPEG_LIBS) -lpthread
LIBDIRS	:=	$(DEKVIT)/usr/lib
LIBDIRS	+=	$(DEKVIT)/usr/include
OUTPUT := ../lgpt-garlic
EXTENSION:= elf

%.elf: $(OFILES)
	$(CXX) $(LDFLAGS) -o $@ $(OFILES) $(LIBS)
	@$(STRIP) $@
