-include $(PWD)/rules_base

%.deb-exe: $(OFILES)
	$(CXX) $(LDFLAGS) $@ $(OFILES) $(LIBS)

CFLAGS	:=  -O3 -DCPP_MEMORY -Wall -I/usr/local/include -I$(PWD)/../sources -D__LINUX_ALSA__ -D__LINUX_ALSASEQ__ -D_DEBUG #-D_NO_JACK_
LIBS	:=  -O3 -L/local/lib -Wl,-rpath,/usr/local/lib -lasound -lSDL -lpthread

#For debugging
#LIBS	:=  -g -L/local/lib -Wl,-rpath,/usr/local/lib -lasound -lSDL -ljack -lpthread
#CFLAGS	:= -g  -DCPP_MEMORY -Wall -I/usr/local/include -I$(PWD)/../sources -D__LINUX_ALSA__ -D__LINUX_ALSASEQ__

CXXFLAGS:= $(CFLAGS)
EXTENSION:= deb-exe
