-include $(PWD)/rules_base

# config
DEFINES := \
	-DPLATFORM_$(PLATFORM) \
	-D_64BIT \
	-DBUFFERED \
	-DCPP_MEMORY \
	-DHAVE_STDINT_H \
	-D_NDEBUG \
	-D_NO_JACK_ \
	-DSDL2 \
        -DSDLAUDIO \
        -DDUMMYMIDI

# ALSA_CFLAGS := $(shell /opt/aarch64-buildroot-linux-gnu_sdk-buildroot/bin/pkg-config alsa --cflags)
# ALSA_LIBS := $(shell /opt/aarch64-buildroot-linux-gnu_sdk-buildroot/bin/pkg-config alsa --libs)

DEVKIT := /opt/aarch64-buildroot-linux-gnu_sdk-buildroot
CROSS_COMPILE:=$(DEVKIT)/bin/aarch64-buildroot-linux-gnu-
# TRIPLET:=aarch64-linux-gnu
TRIPLET:=aarch64-buildroot-linux-gnu/sysroot
CC = $(CROSS_COMPILE)gcc
CXX = $(CROSS_COMPILE)g++
TOOLPATH=$(DEVKIT)/usr/bin
SYSROOT     := $(shell $(CROSS_COMPILE)gcc --print-sysroot)

SDL_CFLAGS  := -I/$(SYSROOT)/include -D_REENTRANT
SDL_LIBS    := -lSDL2

OPT_FLAGS = -O3 -mlittle-endian -mabi=lp64 -march=armv8-a+crypto+crc -fasynchronous-unwind-tables -fstack-protector-strong -Wformat -Wformat-security -fstack-clash-protection -dumpbase
INCLUDES = -Iinclude $(SDL_CFLAGS) -I$(DEVKIT)/$(TRIPLET)/include -I$(DEVKIT)/$(TRIPLET)/include/c++/11/ -I$(PWD)/../sources
CFLAGS	:=	$(DEFINES) $(INCLUDES) $(OPT_FLAGS) -Wall  
CXXFLAGS:=	$(CFLAGS) -std=gnu++03 
LIBS	:= -Wl,-rpath-link,$(DEVKIT)/$(TRIPLET)/lib -Wl,-rpath-link,$(DEVKIT)/$(TRIPLET)/lib/pulseaudio $(SDL_LIBS) -lpthread
OUTPUT = ../lgpt-knulli
EXTENSION:= elf

%.elf: $(OFILES)
	$(CXX) $(LDFLAGS) -o $@ $(OFILES) $(LIBS)
