-include $(PWD)/rules_base

# config
DEFINES := \
        -DPLATFORM_$(PLATFORM) \
        -D_64BIT \
        -DCPP_MEMORY \
        -DSDL2 \
        -DFFMPEG_ENABLED \
    	-DRTAUDIO \
    	-DRTMIDI \
    	-D__MACOSX_CORE__

SDL_CFLAGS := $(shell pkg-config sdl2 --cflags)
SDL_LIBS := $(shell pkg-config sdl2 --libs)

# Override adjustdepends for macOS, for which it is broken
define adjustdepends
endef

# optimization
OPT_FLAGS := -O3
#For debugging
OPT_FLAGS := -g
INCLUDES := $(SDL_CFLAGS) -I$(PWD)/../sources
CFLAGS := $(OPT_FLAGS) $(DEFINES) $(INCLUDES) -Wall
CXXFLAGS := $(CFLAGS) -std=gnu++03
LIBS := $(SDL_LIBS) -framework CoreMIDI -framework CoreFoundation -framework CoreAudio -framework Carbon
OUTPUT := ../lgpt
EXTENSION := apple # .app seems to be reserved and is instantly killed(?)

# build rule
%.apple: $(OFILES)
	$(CXX) $(LDFLAGS) -o $@ $(OFILES) $(LIBS)
