TARGET = lgpt

EXTRA_TARGETS = EBOOT.PBP
PSP_EBOOT_TITLE = LittleGPTracker
PSP_EBOOT_ICON = $(PWD)/psp_icon.png
PSP_EBOOT_ICON1 = $(PWD)/lgpt_icon.bmp
PSP_EBOOT_PIC1 = $(PWD)/psp_bg.png

include $(PWD)/psp_rules

PSPSDK=$(shell $(PSPDEV)/bin/psp-config --pspsdk-path)
PSPBIN = $(PSPSDK)/../bin

CFLAGS	:=	-O3 -G0 -Wall -DPLATFORM_$(PLATFORM) -DNDEBUG -DCPP_MEMORY -I$(PWD)/../sources -I$(PSPSDK)/include

CXXFLAGS:=	$(CFLAGS) -fexceptions -fno-rtti

EXTENSION:= elf

LIBS = -L$(PSPDEV)/psp/lib -lstdc++ -lz -lm -lc -lSDL_image -lpng -lSDL -lGL -lglut -ljpeg
LIBS += -lpspvfpu -lpspgu -lpsphprm -lpsprtc -lpspaudio -lpspirkeyb -lpsppower

