
PATH=$PATH:/home/$(USER)/pspdev/bin/

TARGET = lgpt

EXTRA_TARGETS = EBOOT.PBP
PSP_EBOOT_TITLE = LittleGPTracker
PSP_EBOOT_ICON = $(PWD)/psp_icon.png
PSP_EBOOT_PIC1 = $(PWD)/psp_bg.png

include $(PWD)/psp_rules

PSPSDK=$(shell /home/$(USER)/pspdev/bin/psp-config --pspsdk-path)
PSPBIN = $(PSPSDK)/../bin

CFLAGS	:=	-O3 -G0 -Wall -DPLATFORM_$(PLATFORM) -DNDEBUG -DCPP_MEMORY -I$(PWD)/../sources -I$(PSPSDK)/include

CXXFLAGS:=	$(CFLAGS) -fexceptions -fno-rtti

EXTENSION:= elf

LIBS = -L/home/$(USER)/pspdev/psp/lib -lSDL_image -lpng -lz -lstdc++
LIBS += -lSDL -lGL -lglut -lpspvfpu -lm -lpspgu -lpsphprm -lpspsdk -lpsprtc -lpspaudio -lc -lpspuser -lpsputility -lpspirkeyb -lpsppower -lpspkernel -lpspnet_inet -ljpeg

