-include $(PWD)/rules_base

# config
DEFINES := \
	-DPLATFORM_$(PLATFORM) \
	-D_64BIT \
	-DBUFFERED \
	-DCPP_MEMORY \
	-DHAVE_STDINT_H \
	-D_NDEBUG \
	-D_NO_JACK_ \
	-DSDL2 \
	-DSDLAUDIO \
	-DDUMMYMIDI \
	-DFFMPEG_ENABLED

DEVKIT := /opt/rg35xx-plus-aarch64-SDL2-SDK-0.1.0/
CROSS_COMPILE:=$(DEVKIT)bin/aarch64-none-linux-gnu-
TRIPLET:=aarch64-linux-gnu
CC = $(CROSS_COMPILE)gcc
CXX = $(CROSS_COMPILE)g++
TOOLPATH=$(DEVKIT)/usr/bin

SDL_CFLAGS  := -I/$(SYSROOT)/include -D_REENTRANT
SDL_LIBS    := -lSDL2

FFMPEG_INCL=  libavformat \
              libavfilter \
              libavcodec  \
              libavutil   \

LIBAV_PATH := aarch64-linux-gnu/include
FFMPEG_CFLAGS := -I$(DEVKIT)/$(LIBAV_PATH)/libavformat -I$(DEVKIT)/$(LIBAV_PATH)/libavfilter -I$(DEVKIT)/$(LIBAV_PATH)/libavcodec -I$(SYSROOT)/$(LIBAV_PATH)/libavutil
FFMPEG_LIBS := -lavformat -lavfilter -lavcodec -lavutil

$(info FFMPEG_CFLAGS: $(FFMPEG_CFLAGS))
$(info FFMPEG_LIBS: $(FFMPEG_LIBS))

OPT_FLAGS = -O3 -mlittle-endian -mabi=lp64 -march=armv8-a+crypto+crc -fasynchronous-unwind-tables -fstack-protector-strong -Wformat -Wformat-security -fstack-clash-protection -dumpbase
INCLUDES = -Iinclude $(SDL_CFLAGS) $(FFMPEG_CFLAGS) -I$(DEVKIT)/$(TRIPLET)/include -I$(DEVKIT)/$(TRIPLET)/include/c++/11/ -I$(PWD)/../sources
CFLAGS	:=	$(DEFINES) $(INCLUDES) $(OPT_FLAGS) -Wall  
CXXFLAGS:=	$(CFLAGS) -std=gnu++03 
LIBS	:= -Wl,-rpath-link,$(DEVKIT)/$(TRIPLET)/lib -Wl,-rpath-link,$(DEVKIT)/$(TRIPLET)/lib/pulseaudio $(SDL_LIBS) $(FFMPEG_LIBS) -lpthread
OUTPUT = ../lgpt-rg35xxplus
EXTENSION:= elf

%.elf: $(OFILES)
	$(CXX) $(LDFLAGS) -o $@ $(OFILES) $(LIBS)
